# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 11:00
from __future__ import unicode_literals

import avatars.models
import avatars.storage
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('email_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, storage=avatars.storage.FileOverwriteStorage(), upload_to=avatars.models.avatar_image_path)),
            ],
        ),
    ]
