# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
